# global variables
'''
offSelDIm = False
offNormal = True
offInit =  True
offUpset = False
LEAF_ID = 0
INIDATA_NUM = 250
UPDATE_NORMAL_STEP = 200
MAX_ENTRIES_NUM = 4
#MAX_LEAF_NUM = 4
count = 0
NUM_CLUSTERS = 10
Dim = 256
K_sel = 155
Normalizor = None
MAX_LIMIT_MEMORY = 1024*300
UNCERTAIN_THRESHOLD = 0.9
MAX_UPPERSET_CAPACITY = 200
OUTLIER_THRES = 0.8*MAX_UPPERSET_CAPACITY
OUTLIERS_NUM = 1000
cftree = None
applyRefinement = False
MIN_CLUSTER_SIZE = 20
MAX_NODES = 50
'''
offSelDim =None
offNormal =None
offInit =None
offUpset =None
LEAF_ID =None
INIDATA_NUM =None
UPDATE_NORMAL_STEP =None
MAX_ENTRIES_NUM =None
count =None
NUM_CLUSTERS =None
Dim =None
K_sel =None
Normalizor =None
MAX_LIMIT_MEMORY =None
UNCERTAIN_THRESHOLD =None
MAX_UPPERSET_CAPACITY =None
OUTLIER_THRES =None
OUTLIERS_NUM =None
cftree =None
applyRefinement =None
MIN_CLUSTER_SIZE =None
MAX_NODES =None
ENTRY_LIMIT = None
